name       : dcraw
version    : 9.28.0
release    : 5
source     :
    - http://www.cybercom.net/~dcoffin/dcraw/archive/dcraw-9.28.0.tar.gz : 2890c3da2642cd44c5f3bfed2c9b2c1db83da5cec09cc17e0fa72e17541fb4b9
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Dave Coffin's raw photo decoder
description: |
    This is a command-line ANSI C program to convert raw photos from any digital camera on any computer running any operating system.
builddeps  :
    - pkgconfig(lcms2)
    - jasper-devel
    - libjpeg-turbo-devel
build      : |
    gcc %CFLAGS% %LDFLAGS% \
        -o dcraw dcraw.c \
        -lm -ljasper -ljpeg -llcms2 \
        -DLOCALEDIR=\"%PREFIX%/share/locale/\"
install    : |
    install -Dm755 dcraw %installroot%/usr/bin/dcraw
    install -Dm644 dcraw.1 %installroot%/usr/share/man/man1/dcraw.1
    for i in dcraw_*.1; do j=${i#dcraw_}; k=${j%.1}
        install -Dm644 $i %installroot%/usr/share/man/$k/man1/dcraw.1
    done
    for i in dcraw_*.po; do j=${i#dcraw_}; k=${j%.po}
        install -d %installroot%/usr/share/locale/$k/LC_MESSAGES
        msgfmt -o %installroot%/usr/share/locale/$k/LC_MESSAGES/dcraw.mo $i
    done
    install -d %installroot%/usr/share/licenses/dcraw
    head -25 dcraw.c > %installroot%/usr/share/licenses/dcraw/license.txt
