name       : dcraw
version    : 9.28.0
release    : 6
source     :
    - https://www.dechifro.org/dcraw/archive/dcraw-9.28.0.tar.gz : 2890c3da2642cd44c5f3bfed2c9b2c1db83da5cec09cc17e0fa72e17541fb4b9
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Tool for decoding raw image data from digital cameras
description: |
    This is a command-line ANSI C program to convert raw photos from any digital camera on any computer running any operating system.
builddeps  :
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - pkgconfig(libturbojpeg)
build      : |
    gcc %CFLAGS% %LDFLAGS% \
        -o dcraw dcraw.c \
        -lm -ljasper -ljpeg -llcms2 \
        -DLOCALEDIR=\"/usr/share/locale/\"
install    : |
    install -Dm00755 dcraw $installdir/usr/bin/dcraw
    install -Dm00644 dcraw.1 $installdir/usr/share/man/man1/dcraw.1
    for i in dcraw_*.1; do j=${i#dcraw_}; k=${j%.1}
        install -Dm00644 $i $installdir/usr/share/man/$k/man1/dcraw.1
    done
    for i in dcraw_*.po; do j=${i#dcraw_}; k=${j%.po}
        install -dm00755  $installdir/usr/share/locale/$k/LC_MESSAGES
        msgfmt -o $installdir/usr/share/locale/$k/LC_MESSAGES/dcraw.mo $i
    done
